name: Scheduled Ingestion

on:
  schedule:
    # Run every 3 hours (at 0:00, 3:00, 6:00, 9:00, 12:00, 15:00, 18:00, 21:00 UTC)
    - cron: '0 */3 * * *'
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ingestion on Fly.io
        run: |
          echo "Triggering ingestion at $(date)"
          curl -X POST "https://opennotenetwork-api.fly.dev/api/admin/ingest?batch_size=50&max_total_posts=500" \
            -H "Content-Type: application/json" \
            -w "\nHTTP Status: %{http_code}\n" \
            -s -o response.json

          echo "Response:"
          cat response.json

      - name: Check response
        run: |
          if grep -q '"status":"started"' response.json || grep -q '"job_id"' response.json; then
            echo "✅ Ingestion triggered successfully"
          else
            echo "❌ Ingestion may have failed"
            cat response.json
            exit 1
          fi
